import { Analytics } from "@vercel/analytics/next";
import { Footer, Layout, Navbar } from "nextra-theme-docs";
import { Head } from "nextra/components";
import { getPageMap } from "nextra/page-map";
import "./globals.css";

export const metadata = {
  title: {
    default: "CTDOCS",
    template: "%s | CTDOCS",
  },
  description: "Generated by create next app",
};

const navbar = (
  <Navbar
    logo={<p>CTDOCS</p>}
    projectLink="https://github.com/teerakanotk/ctdocs.git"
  />
);

const footer = <Footer>© {new Date().getFullYear()} CTdocs</Footer>;

export default async function RootLayout({ children }) {
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <Head />
      <body>
        <Layout
          navbar={navbar}
          pageMap={await getPageMap()}
          docsRepositoryBase="https://github.com/teerakanotk/ctdocs/tree/main"
          footer={footer}
          sidebar={{ toggleButton: false, defaultMenuCollapseLevel: 1 }}
        >
          {children}
        </Layout>
        <Analytics />
      </body>
    </html>
  );
}
