import type { Metadata } from "next";
import "./globals.css";

import { Footer, Layout, Navbar } from "nextra-theme-docs";
import { Head } from "nextra/components";
import { getPageMap } from "nextra/page-map";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navbar = (
  <Navbar
    logo={<b>CTDOCS</b>}
    projectLink="https://github.com/teerakanotk/ctdocs"
  />
);
const footer = <Footer>MIT {new Date().getFullYear()} © CTDOCS.</Footer>;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <Head />
      <body>
        <Layout
          navbar={navbar}
          pageMap={await getPageMap()}
          docsRepositoryBase="https://github.com/teerakanotk/ctdocs/tree/main"
          footer={footer}
          sidebar={{ defaultMenuCollapseLevel: 1, toggleButton: false }}
        >
          {children}
        </Layout>
      </body>
    </html>
  );
}
