import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";

import { Layout, Navbar } from "nextra-theme-docs";
import { Head } from "nextra/components";
import { getPageMap } from "nextra/page-map";

export const metadata: Metadata = {
  title: {
    default: "CTDOCS",
    template: "%s | CTDOCS",
  },
  description: "Generated by create next app",
};

const prompt = Prompt({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "thai"],
});

const navbar = (
  <Navbar
    logo={<b>CTDOCS</b>}
    projectLink="https://github.com/teerakanotk/ctdocs"
  />
);

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <Head />
      <body className={`${prompt.className} antialiased`}>
        <Layout
          navbar={navbar}
          pageMap={await getPageMap()}
          docsRepositoryBase="https://github.com/teerakanotk/ctdocs/tree/main"
          sidebar={{ defaultMenuCollapseLevel: 1, toggleButton: false }}
        >
          {children}
        </Layout>
      </body>
    </html>
  );
}
